config/routes.rb
Rails.application.routes.draw do
  resources :users, except: [:new]
  get 'register' => 'users#new'
  root 'pages#welcome'
  resources :pages
  resources :sessions, except: [:new, :create, :destroy]
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'
  resources :clans do
    member do
      post 'attack'
    end
  end
  resources :resources do 
    member do
      post 'purchase'
    end
  end
  resources :relationships
end

app/models/clan.rb
class Clan < ActiveRecord::Base
	belongs_to :user
	has_many :passive_relationships, class_name: "Relationship",
									 foreign_key: "clan_id",
									 dependent: :destroy
	has_many :members, through: :passive_relationships, source: :member
end

app/models/purchase.rb
class Purchase < ActiveRecord::Base
	belongs_to :user
	belongs_to :resource
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
	belongs_to :member, class_name: "User"
	belongs_to :clan, class_name: "Clan"
end

app/models/resource.rb
class Resource < ActiveRecord::Base
	belongs_to :user
	has_many :purchases
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :clans
	has_many :resources
	has_many :purchases

	has_many :active_relationships, class_name: "Relationship",
									foreign_key: "member_id",
									dependent: :destroy

	has_many :memberships, through: :active_relationships, source: :clan
	def join(clan)
		active_relationships.create(clan_id: clan.id)
		clan.power = clan.power += 10
		clan.save
	end
	def unjoin(clan)
		active_relationships.find_by(clan: clan).destroy
		clan.power = clan.power -= 10
		clan.save
	end
	def member?(clan)
		memberships.include?(clan)
	end
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  def logged_in?
  	!!current_user
  end

end

app/controllers/clans_controller.rb
class ClansController < ApplicationController
	def new
		@clan = Clan.new
	end
	def index
		@clans = Clan.all
	end
	def show
		@clan = Clan.find(params[:id])
		@relationships = @clan.passive_relationships
	end
	def create
		@clan = Clan.new(clan_params)
		@clan.user = User.find(current_user)
		@clan.power = 50
		if @clan.save
			redirect_to clans_path
		else
			render 'new'
		end
	end
	def attack
		user = User.find(current_user.id)
		@clan = Clan.find(params[:id])
		@clan.power = (@clan.power -= user.attack if user.attack)
		if @clan.save && @clan.power > 0
			redirect_to :back
		else
			@clan.destroy
			redirect_to clans_path
		end
	end


	private
		def clan_params
			params.require(:clan).permit(:name,:description,:user_id, :power)
		end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def welcome
	end

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
	def create
		clan = Clan.find(params[:clan_id])
		current_user.join(clan)
		redirect_to :back
	end
	def destroy
		clan = Relationship.find(params[:id]).clan
		current_user.unjoin(clan)
		redirect_to :back
	end

end

app/controllers/resources_controller.rb
class ResourcesController < ApplicationController
	def index
		@resources = Resource.all
	end
	def show
		@resource = Resource.find(params[:id])
	end
	def purchase
		@resource = Resource.find(params[:id])
		@user = User.find(current_user)
		purchase = Purchase.create(user: @user, resource: @resource)
		if purchase.valid?
			redirect_to :back
		else
			#do something else
		end
	end
	def create
		@resource = Resouce.new(resource_params)
		if @resource.save
			redirect_to user_path(current_user)
		else
			redirect_to :back
		end
	end

	private
		def resource_params
			params.require(:resource).permit(:name,:description, :price, :user_id)
		end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController


	def new
	end

	def create
		user = User.find_by(email: params[:email])
		if user && user.authenticate(params[:password])
			session[:user_id] = user.id
			redirect_to root_path
		else
			render 'new'
		end
	end

	def destroy
		session[:user_id] = nil
		redirect_to root_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def show
		@user = User.find(params[:id])
	end
	def new
		@user = User.new
	end
	def create
		@user = User.new(user_params)
		@user.attack = 2
		if @user.save
			redirect_to login_path
		else
			render 'new'
		end
	end

	private
		def user_params
			params.require(:user).permit(:name,:username,:email,:password, :affiliation, :attack)
		end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/clans/index.html.erb
<%= link_to "New Clan", new_clan_path %>
<h1>Clans</h1>

<% @clans.each do |clan| %>
	<%= link_to clan.name, clan_path(clan) %>
	<%= clan.user.username if clan.user %>
	<%= clan.passive_relationships.count %><br>
<% end %>

app/views/clans/new.html.erb
<h1>Create a Clan</h1>

<%= form_for @clan do |form| %>
	<%= form.text_field :name, placeholder: "Clan Name" %>
	<%= form.text_field :description, placeholder: "Clan Description" %>
	<%= form.submit "Create"%>
<% end %>

app/views/clans/show.html.erb
<h1><%= @clan.name %></h1>
<% if logged_in? %>
	<% if current_user.active_relationships.find_by(clan_id: @clan.id) %>
	<%= form_for(current_user.active_relationships.find_by(clan_id: @clan.id), html: {method: :delete}) do |f| %>
		<div><%= f.submit "unJoin" %></div>
	<% end %>
	<% else %>
	<%= form_for(current_user.active_relationships.build(clan_id: @clan.id)) do |f| %>
		<%= hidden_field_tag :clan_id, @clan.id %>
		<div><%= f.submit "Join" %></div>
		<% end %>
	<%= link_to "Attack", attack_clan_path, method: :post %>
	<% end %>
<% end %>
<h3>Members</h3>
<% @relationships.each do |relationship| %>
	<%= relationship.member.name %>
<% end %><br>
<b>Power: </b><%= @clan.power if @clan.power %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StrategyGameApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'shared/navigation' %>
<%= yield %>

</body>
</html>

app/views/pages/welcome.html.erb
<h1>Strategy Game</h1>

app/views/resources/index.html.erb
<h1>Resources</h1>

<% @resources.each do |resource| %>
	<%= link_to resource.name, resource_path(resource) %>
	
<% end %>

app/views/resources/show.html.erb
<h1><%= @resource.name %></h1><br>
<%= @resource.description %>
<%= form_tag(purchase_resource_path, method: 'post') do %>
	<%= submit_tag "buy one" %>
<% end %>

app/views/shared/_navigation.html.erb
<%= link_to "Home", root_path %>
<% if current_user %>
	<%= link_to "Profile", user_path(current_user) %>
	<%= current_user.username %>
	<%= link_to "Logout", logout_path %>
	<%= link_to "Clans", clans_path %>
	<%= link_to "Resources", resources_path %>
<% else %>
	<%= link_to "Overview", root_path %>
	<%= link_to "Login", login_path %>
	<%= link_to "Register", register_path %>
<% end %>

app/views/users/new.html.erb
<h1>Register!</h1>

<%= form_for @user do |form| %>
	<%= form.text_field :name, placeholder: "Name" %>
	<%= form.text_field :username, placeholder: "Username" %>
	<%= form.email_field :email, placeholder: "Email" %>
	<%= form.password_field :password, placeholder: "Password" %>
	<%= form.select :affiliation, ["Mage","Assasin","Archer","Knight"] %>
	<%= form.submit "Register" %>
<% end %>

app/views/users/show.html.erb
<br>
<h1><b><%= @user.username %></b></h1>
<b>Class: </b><%= @user.affiliation %><br>
<b>Clans: </b>
<% @user.active_relationships.each do |relationship| %>
	<%= relationship.clan.name %>
<% end %>